package tk.netindev.zeronet.service.util

enum class ConnectionStatus {
    LEVEL_CONNECTED,
    LEVEL_CONNECTING_SERVER_REPLIED,
    LEVEL_CONNECTING_NO_SERVER_REPLY_YET,
    LEVEL_NO_NETWORK,
    LEVEL_NOT_CONNECTED,
    LEVEL_START,
    LEVEL_AUTH_FAILED,
    LEVEL_CONNECTING_DNS,
    LEVEL_CONNECTING_SSH,
    LEVEL_AUTHENTICATING,
    LEVEL_TUNNEL_SETUP,
    LEVEL_DISCONNECTING,
    LEVEL_RECONNECTING,
    LEVEL_TIMEOUT,
    LEVEL_PROXY_ERROR,
    UNKNOWN_LEVEL
}
